baseURL = "https://gnk263.net/"
languageCode = "ja"
title = "艦これアプリ工廠"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "プライバシーポリシー"
url = "/poricy"
weight = 100

[[menu.shortcuts]]
name = "問い合わせ"
url = "/contact"
weight = 110
