baseURL = "https://gnk263.net/"
languageCode = "ja"
title = "艦これアプリ工廠"
theme = "hugo-theme-learn"

[params]
author = "gnk263"
description = "艦これに関するスマートフォン（iOS/Android）向けのアプリケーションを配布しています。明石の工廠向けの改修アプリ、資源・資材を管理しグラフ表示するアプリなどがあります。"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "プライバシーポリシー"
url = "/poricy"
weight = 100

[[menu.shortcuts]]
name = "問い合わせ"
url = "/contact"
weight = 110
